// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:atwoz_app/app/constants/enum.dart';
import 'package:atwoz_app/features/auth/data/dto/user_response.dart';
import 'package:atwoz_app/features/home/data/dto/introduced_profile_dto.dart';
import 'package:atwoz_app/features/home/domain/model/cached_user_profile.dart';
import 'package:atwoz_app/features/my/domain/model/my_profile_image.dart';
import 'package:atwoz_app/features/profile/domain/common/enum.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedUserProfileAdapter());
    registerAdapter(DrinkingStatusAdapter());
    registerAdapter(EducationAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(HobbyAdapter());
    registerAdapter(InterviewInfoAdapter());
    registerAdapter(IntroducedProfileDtoAdapter());
    registerAdapter(JobAdapter());
    registerAdapter(MyProfileImageAdapter());
    registerAdapter(ReligionAdapter());
    registerAdapter(SmokingStatusAdapter());
    registerAdapter(UserDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedUserProfileAdapter());
    registerAdapter(DrinkingStatusAdapter());
    registerAdapter(EducationAdapter());
    registerAdapter(GenderAdapter());
    registerAdapter(HobbyAdapter());
    registerAdapter(InterviewInfoAdapter());
    registerAdapter(IntroducedProfileDtoAdapter());
    registerAdapter(JobAdapter());
    registerAdapter(MyProfileImageAdapter());
    registerAdapter(ReligionAdapter());
    registerAdapter(SmokingStatusAdapter());
    registerAdapter(UserDataAdapter());
  }
}
