// TODO: api 생기면 삭제 예정
final jobOptions = [
  '연구개발/엔지니어',
  '개인사업/자영업',
  '영업/판매',
  '경영/기획',
  '미래를 위한 공부중',
  '취업 준비중',
  '교육',
  '예술/체육',
  '요식업',
  '의료/보건',
  '기계/건설',
  '디자인',
  '마케팅/광고',
  '무역/유통',
  '방송언론/연예',
  '법률/공공',
  '생산/제조',
  '서비스',
  '여행/운송',
  '기타'
];

final hobbies = [
  '국내여행/해외여행',
  '공연/전시회관람',
  '웹툰/만화',
  '드라마/예능보기',
  'PC/모바일게임',
  '애니메이션',
  '골프',
  '연극/영화',
  '글쓰기',
  '러닝',
  '보드게임',
  '사진촬영',
  '노래',
  '배드민턴/테니스',
  '댄스',
  '드라이브',
  '등산/클라이밍',
  '산책',
  '맛집탐방',
  '쇼핑',
  '스키/스노우보드',
  '악기연주',
  '와인',
  '운동/헬스',
  '요가/필라테스',
  '요리',
  '인테리어',
  '자전거',
  '캠핑',
  '기타',
];

const hobbyLabelToEnumKey = {
  "국내여행/해외여행": "TRAVEL",
  "공연/전시회관람": "PERFORMANCE_AND_EXHIBITION",
  "웹툰/만화": "WEBTOON_AND_COMICS",
  "드라마/예능보기": "DRAMA_AND_ENTERTAINMENT",
  "PC/모바일게임": "PC_AND_MOBILE_GAMES",
  "애니메이션": "ANIMATION",
  "골프": "GOLF",
  "연극/영화": "THEATER_AND_MOVIES",
  "글쓰기": "WRITING",
  "보드게임": "BOARD_GAMES",
  "사진촬영": "PHOTOGRAPHY",
  "노래": "SINGING",
  "배드민턴/테니스": "BADMINTON_AND_TENNIS",
  "댄스": "DANCE",
  "드라이브": "DRIVING",
  "등산/클라이밍": "HIKING_AND_CLIMBING",
  "산책": "WALKING",
  "맛집탐방": "FOOD_HUNT",
  "쇼핑": "SHOPPING",
  "스키/스노우보드": "SKI_AND_SNOWBOARD",
  "악기연주": "PLAYING_INSTRUMENTS",
  "와인": "WINE",
  "운동/헬스": "WORKOUT",
  "요가/필라테스": "YOGA_AND_PILATES",
  "요리": "COOKING",
  "인테리어": "INTERIOR_DESIGN",
  "자전거": "CYCLING",
  "캠핑": "CAMPING",
  "기타": "OTHERS",
};

const jobLabelToEnumKey = {
  "연구개발/엔지니어": "RESEARCH_AND_ENGINEERING",
  "개인사업/자영업": "SELF_EMPLOYMENT",
  "영업/판매": "SALES",
  "경영/기획": "MANAGEMENT_AND_PLANNING",
  "미래를 위한 공부중": "STUDYING_FOR_FUTURE",
  "취업 준비중": "JOB_SEARCHING",
  "교육": "EDUCATION",
  "예술/체육": "ARTS_AND_SPORTS",
  "요식업": "FOOD_SERVICE",
  "의료/보건": "MEDICAL_AND_HEALTH",
  "기계/건설": "MECHANICAL_AND_CONSTRUCTION",
  "디자인": "DESIGN",
  "마케팅/광고": "MARKETING_AND_ADVERTISING",
  "무역/유통": "TRADE_AND_DISTRIBUTION",
  "방송언론/연애": "MEDIA_AND_ENTERTAINMENT",
  "법률/공공": "LEGAL_AND_PUBLIC",
  "생산/제조": "PRODUCTION_AND_MANUFACTURING",
  "서비스": "CUSTOMER_SERVICE",
  "여행/운송": "TRAVEL_AND_TRANSPORT",
  "기타": "OTHERS",
};

const cityNameToEnumKey = {
  "서울특별시": "SEOUL",
  "인천광역시": "INCHEON",
  "부산광역시": "BUSAN",
  "대전광역시": "DAEJEON",
  "대구광역시": "DAEGU",
  "광주광역시": "GWANGJU",
  "울산광역시": "ULSAN",
  "제주특별자치도": "JEJU",
  "세종특별자치도": "SEJONG",
  "강원도": "GANGWON",
  "경기도": "GYEONGGI",
  "경상남도": "GYEONGSANGNAM",
  "경상북도": "GYEONGSANGBUK",
  "충청남도": "CHUNGCHEONGNAM",
  "충청북도": "CHUNGCHEONGBUK",
  "전라남도": "JEOLLANAM",
  "전라북도": "JEOLLABUK",
};
