name: Flutter_Test

on:
  pull_request:
    branches:
      - prod
      - dev
      - main
# Job 영역
jobs:
  build:
    name: Running Test and CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Flutter SDK 설치
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"

      # Step 3: GitHub Secrets를 사용하여 .env 파일 생성
      - name: Create .env file
        run: |
      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> dev.env
          echo "DEEP_LINK_URL=${{ secrets.DEEP_LINK_URL }}" >> dev.env

      # Step 4: Flutter 의존성 가져오기
      - name: Get Flutter Dependencies
        run: flutter pub get

      # Step 5: Flutter 테스트 실행
      - name: Run Flutter Tests
        run: |
          flutter test --coverage || { echo "Tests failed"; exit 1; }

      # Step 6: Flutter 의존성 캐싱
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
